[[ips]]
ip = "${IP}"
comment = "gsuiteidstream/pushnotification-app - This is the reserved IP for pushnotification service"
project = "gsuiteidstream"
datacenters = ["${DATACENTER}"]

[[firewalls]]
name = "pushnotification-fw-prod.gsuiteidstream"
datacenters = ["${DATACENTER}"]

[[firewalls.rules]]
resources = ["0.0.0.0/0"]
ports = [80]
protocols = ["tcp"]

[[pools]]
name = "pushnotification-bk-prod.gsuiteidstream"
image = "gsuiteidstream/pushnotification-app"
cpu = 2.0
memory = 5120
tag = "prod"
host_tag = "default"
instances = 1
kill_timeout = 3600
deploy_step_size = 1
save_empty_deploys = 2
datacenters = ["${DATACENTER}"]

[[pools.firewall.in]]
firewall = "pushnotification-fw-prod.gsuiteidstream"
mode = "allow"

[pools.healthcheck]
protocol="http"
path="/identity/v1/status"
port=80
timeout=2
rise=3
fall=3

[[pools]]
name = "pushnotification-lb-prod.gsuiteidstream"
image = "quadra/http-lb"
cpu = 2.0
memory = 4096
tag = "latest"
instances = 1
deploy_step_size = 1
save_empty_deploys = 1
datacenters = ["${DATACENTER}"]
ipv4 = "${IP}"

[[pools.firewall.in]]
firewall = "pushnotification-fw-prod.gsuiteidstream"
mode = "allow"

[pools.healthcheck]
protocol="https"
path="/backend_status"
port=443
timeout=2
rise=3
fall=3

[pools.environment]
BACKEND_POOL="pushnotification-bk-prod.gsuiteidstream"
BACKEND_PORT=80
BACKEND_CHECK_URL= "/identity/v1/status"
SSL_PORT = 443
REDIRECT_TO_SSL = true
VINZ_CERT_ID = "${REQUEST_ID_PROD}"
SECRET_VINZ_DEPLOY_KEY = "${DEPLOYKEY_PROD}"
VINZ_API = "https://api.vinz.opendns.com/v1"
SSL_CIPHERS = "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:SRP-DSS-AES-256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:DHE-DSS-AES256-SHA256:DHE-RSA-CAMELLIA256-SHA:DHE-DSS-CAMELLIA256-SHA:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:SRP-DSS-AES-128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:DHE-DSS-AES128-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-DSS-CAMELLIA128-SHA:CAMELLIA128-SHA:DES-CBC3-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305"
SSL_PROTOCOLS = "TLSv1 TLSv1.1 TLSv1.2"
