apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: '${BACKEND_CHECK_URL}'
        backend:
          serviceName: test
  ports:
    - protocol: TCP
      port: 6379